############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Blog"
url = "/blog"
weight = 2

[[main]]
name = "Status"
url = "/status"
weight = 4

[[main]]
name = "About Me"
url = "/about"
weight = 5

# footer menu

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 1
