#################### default parameters ############################
favicon = "images/favicon.png"
logo = "images/logo_jlv6_light.png"
logo_darkmode = "images/logo_jlv6_dark.png"
logo_width = "66px"
logo_height = "49px"
# logo text will only show when logo is missing.
logo_text = "jlv6.com"
navbar_fixed = true
theme_switcher = true
theme_default = "system"
# Main Sections
mainSections = ["blog"]
# contact form action
## contact_form_action = ""
# google tag manager, see https://developers.google.com/tag-manager/
## google_tag_manager = ""
## google_adsense = ""
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
## custom_script = ""
# copyright
## copyright = ""

# Preloader
# preloader module: https://github.com/gethugothemes/hugo-modules/tree/master/components/preloader
[preloader]
enable = false
## preloader = ""

# Navigation button
[navigation_button]
enable = true
label = "Dashboard"
link = "https://dashboard-www.jlv6.com"

# search
# search module: https://github.com/gethugothemes/hugo-modules/tree/master/search
[search]
enable = true
primary_color = "#121212"
include_sections = ["blog"]
show_image = true
show_description = true
show_tags = true
show_categories = true

# announcement
# announcement module: https://github.com/gethugothemes/hugo-modules/tree/master/components/announcement
[announcement]
enable = false
## expire_days = 7
## content = ""

# seo meta data for OpenGraph / Twitter Card
# seo module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/basic-seo
[metadata]
## keywords = ["Boilerplate", "Hugo"]
## description = "Hugo & Tailwindcss Starter"
## author = "zeon.studio"
## twitter = "zeon_studio"
## image = "images/og-image.png"

# cookies
# cookies module: https://github.com/gethugothemes/hugo-modules/tree/master/components/cookie-consent
[cookies]
enable = false
## expire_days = 60
## content = "This site uses cookies. By continuing to use this website, you agree to their use."
## button = "I Accept"

# diagrams
## [mermaid]
## js_url = 'https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs'

######################## sidebar widgets #########################
[widgets]
sidebar = ["categories", "tags"]

# google map
[google_map]
enable = false
## map_api_key = ""
## map_latitude = ""
## map_longitude = ""
## map_marker = ""

# Subscription
[subscription]
enable = false
# mailchimp subsciption
## mailchimp_form_action = ""
## mailchimp_form_name = ""
