name: build_deploy_onprem

env:
  REGISTRY_IMAGE: "${{ vars.FORGEJO_REGISTRY01 }}/${{ vars.FORGEJO_OWNER01 }}/${{ vars.IMAGE_NAME }}"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
      
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:

  build-image:
    environment: production
    strategy:
      matrix:
        platform:
          - amd64
          - arm64
        include:
          - platform: amd64
            runner: x64
          - platform: arm64
            runner: arm64
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
       - name: Get Docker metadata
         id: meta
         uses: docker/metadata-action@v5
         with:
           images: |
             ${{ vars.FORGEJO_REGISTRY01 }}/${{ vars.FORGEJO_OWNER01 }}/${{ vars.IMAGE_NAME }}
           tags: |
             type=schedule
             type=ref,event=branch
             type=ref,event=pr
             type=semver,pattern={{version}}
             type=semver,pattern={{major}}.{{minor}}
             type=semver,pattern={{major}}
             type=sha
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to forgejo
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.FORGEJO_REGISTRY01 }}
          username: ${{ secrets.FORGEJO_USER01 }}
          password: ${{ secrets.FORGEJO_USER01_PAT }}
      - name: Build and Push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/docker/Dockerfile
          build-args: |
            "JLV6_UID=${{ vars.JLV6_UID }}"
            "JLV6_USER=${{ vars.JLV6_USER }}"
            "JLV6_GID=${{ vars.JLV6_GID }}"
            "JLV6_GROUP=${{ vars.JLV6_GROUP }}"
          platforms: linux/${{ matrix.platform }}
          push: true
          cache-from: type=gha,scope=build-${{ github.event.repository.name }}-${{ vars.ENVIRONMENT }}-${{ matrix.platform }}
          cache-to: type=gha,mode=max,scope=build-${{ github.event.repository.name }}-${{ vars.ENVIRONMENT }}-${{ matrix.platform }}
          provenance: false
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            "${{ steps.meta.outputs.tags }}"
            "${{ env.REGISTRY_IMAGE }}:${{ inputs.DATE }}-${{ vars.ENVIRONMENT }}-${{ matrix.platform }}"

  build-merge:
    environment: production
    runs-on: self-hosted
    needs: build-image
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to forgejo
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.FORGEJO_REGISTRY01 }}
          username: ${{ secrets.FORGEJO_USER01 }}
          password: ${{ secrets.FORGEJO_USER01_PAT }}
      - name: Create manifest list and push
        run: |
          docker buildx imagetools create -t ${{ env.REGISTRY_IMAGE }}:${{ inputs.DATE }}-${{ vars.ENVIRONMENT }} \
            ${{ env.REGISTRY_IMAGE }}:${{ inputs.DATE }}-${{ vars.ENVIRONMENT }}-amd64 \
            ${{ env.REGISTRY_IMAGE }}:${{ inputs.DATE }}-${{ vars.ENVIRONMENT }}-arm64
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ inputs.DATE }}-${{ vars.ENVIRONMENT }}

  deploy:
    environment: production
    runs-on: self-hosted
    if: success()
    needs: build-merge
    steps:
      - name: Checkout k8s.git
        uses: actions/checkout@v4
        with:
          repository: v6Org01/k8s
          ref: main
          token: ${{ secrets.GHA_PAT }}
          sparse-checkout: |
            .github/actions
            ${{ vars.ARGOCD_CUSTOM_DIR }}
      - name: Update image tag and deploy app with ArgoCD
        uses: ./.github/actions/update-imageTag-argoDeploy
        with:
          FILE_PATH: ${{ vars.ARGOCD_CRD_APP_PATH }} 
          KUBECONFIG: ${{ secrets.KUBECONFIG_PRIV }}
          NAMESPACE: ${{ vars.NAMESPACE }}
          VERSION: ${{ inputs.DATE }}-${{ vars.ENVIRONMENT }}
