name: deploy_staging_to_k8s

on:
  workflow_call:
    inputs:
      VERSION:
        description: 'Application version'
        required: true
        type: string
    secrets:
      DEPLOY_PRIVATE_KEY:
        required: true
      KUBECONFIG_PLUTO_STAGING:
        required: true

jobs:

  update-argocd-app:
    runs-on: gha-runner-scale-set-arm64
    environment: staging
    steps:
      - name: Update image tag and deploy app with ArgoCD
        uses: v6Org01/.github/actions/update-imageTag-argoDeploy@main
        with:
          ARGOCD_APPLICATION_FILE: ${{ vars.ARGOCD_APPLICATION_FILE }}
          DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          KUBECONFIG: ${{ secrets.KUBECONFIG_PLUTO_STAGING }}
          NAMESPACE: ${{ vars.K8S_NAMESPACE }}
          VERSION: ${{ inputs.VERSION }}

  forward-var-version:
    runs-on: gha-runner-scale-set-arm64
    outputs:
      VERSION: ${{ steps.set-output-version.outputs.VERSION }}
    steps:
      - name: Set output VERSION
        id: set-output-version
        run: |
          echo "VERSION=${{ inputs.VERSION }}" >> $GITHUB_OUTPUT

  check-cancelled:
    runs-on: gha-runner-scale-set-arm64
    needs: tf-shared-apply-run
    outputs:
      IS_CANCELLED: ${{ steps.set-output-cancelled.outputs.IS_CANCELLED }}
    steps:
      - name: Set output IS_CANCELLED
        id: set-output-cancelled
        if: ${{ cancelled() }}
        run: |
          echo "IS_CANCELLED=true" >> $GITHUB_OUTPUT