name: deploy_production_to_k8s

on:
  workflow_call:
    inputs:
      VERSION:
        description: 'Application version'
        required: true
        type: string
    secrets:
      DEPLOY_PRIVATE_KEY:
        required: true
      KUBECONFIG_PLUTO_PROD:
        required: true

jobs:

  update-argocd-app:
    runs-on: gha-runner-scale-set-arm64
    environment: production
    steps:
      - name: Update image tag and deploy app with ArgoCD
        uses: v6Org01/.github/actions/update-imageTag-argoDeploy@main
        with:
          ARGOCD_APPLICATION_FILE: ${{ vars.ARGOCD_APPLICATION_FILE }}
          DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          KUBECONFIG: ${{ secrets.KUBECONFIG_PLUTO_PROD }}
          NAMESPACE: ${{ vars.K8S_NAMESPACE }}
          VERSION: ${{ inputs.VERSION }}